spring.application.name=springdataapp

server.port=1001

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5434/springdataappdatabase

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

spring.mvc.hiddenmethod.filter.enabled=true